#!/usr/bin/env bash

set -euo pipefail

repo_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source_file="$repo_dir/codex/AGENTS.md"
target_dir="${CODEX_HOME:-$HOME/.codex}"
target_file="$target_dir/AGENTS.md"
private_file="$target_dir/AGENTS.private.md"
skills_source_dir="$repo_dir/codex/skills"
skills_target_dir="$HOME/.agents/skills"
guidance_source_dir="$repo_dir/codex/guidance"
guidance_target_dir="$target_dir/guidance/public"
agents_source_dir="$repo_dir/codex/agents"
agents_target_dir="$target_dir/agents"
timestamp="$(date -u +%Y%m%dT%H%M%SZ)"
generated_marker="<!-- Generated by dotfiles/install.sh from public and private guidance. -->"

mkdir -p "$target_dir" "$skills_target_dir" "$agents_target_dir" "$guidance_target_dir"

install_link() {
    local source_path="$1"
    local target_path="$2"

    if [[ -L "$target_path" ]] &&
       [[ "$(readlink -f -- "$target_path")" == "$(readlink -f -- "$source_path")" ]]; then
        printf '%s\n' "Already linked: $target_path"
        return
    fi

    if [[ -e "$target_path" || -L "$target_path" ]]; then
        local backup_path="$target_path.backup.$timestamp"
        mv -- "$target_path" "$backup_path"
        printf '%s\n' "Preserved existing path: $backup_path"
    fi

    ln -s -- "$source_path" "$target_path"
    printf '%s\n' "Linked: $target_path -> $source_path"
}

install_file() {
    local source_path="$1"
    local target_path="$2"

    if [[ -f "$target_path" && ! -L "$target_path" ]] &&
       cmp -s -- "$source_path" "$target_path"; then
        chmod 600 -- "$target_path"
        printf '%s\n' "Already installed: $target_path"
        return
    fi

    if [[ -e "$target_path" || -L "$target_path" ]]; then
        local backup_path="$target_path.backup.$timestamp"
        mv -- "$target_path" "$backup_path"
        printf '%s\n' "Preserved existing path: $backup_path"
    fi

    install -m 600 -- "$source_path" "$target_path"
    printf '%s\n' "Installed: $target_path"
}

for agent_source in "$agents_source_dir"/*.toml; do
    [[ -f "$agent_source" ]] || continue
    install_file "$agent_source" "$agents_target_dir/$(basename -- "$agent_source")"
done

for guidance_source in "$guidance_source_dir"/*.md; do
    [[ -f "$guidance_source" ]] || continue
    install_file "$guidance_source" "$guidance_target_dir/$(basename -- "$guidance_source")"
done

for skill_source in "$skills_source_dir"/*; do
    [[ -d "$skill_source" ]] || continue
    install_link "$skill_source" "$skills_target_dir/$(basename -- "$skill_source")"
done


if [[ -s "$private_file" ]]; then
    temporary_file="$(mktemp "$target_dir/.AGENTS.md.XXXXXX")"
    {
        printf '%s\n\n' "$generated_marker"
        cat -- "$source_file"
        printf '\n\n'
        cat -- "$private_file"
    } > "$temporary_file"

    if [[ -f "$target_file" && ! -L "$target_file" ]] && cmp -s -- "$temporary_file" "$target_file"; then
        rm -- "$temporary_file"
        printf '%s\n' "Already generated: $target_file"
        exit 0
    fi

    if [[ -e "$target_file" || -L "$target_file" ]]; then
        if [[ -L "$target_file" && "$(readlink -f -- "$target_file")" == "$(readlink -f -- "$source_file")" ]]; then
            rm -- "$target_file"
        elif [[ -f "$target_file" && ! -L "$target_file" && "$(head -n 1 -- "$target_file")" == "$generated_marker" ]]; then
            rm -- "$target_file"
        else
            backup_file="$target_file.backup.$(date -u +%Y%m%dT%H%M%SZ)"
            mv -- "$target_file" "$backup_file"
            printf '%s\n' "Preserved existing file: $backup_file"
        fi
    fi

    mv -- "$temporary_file" "$target_file"
    printf '%s\n' "Generated: $target_file from $source_file and $private_file"
    exit 0
fi

if [[ -e "$target_file" || -L "$target_file" ]]; then
    if [[ "$(readlink -f -- "$target_file")" == "$(readlink -f -- "$source_file")" ]]; then
        printf '%s\n' "Already linked: $target_file"
        exit 0
    fi

    backup_file="$target_file.backup.$(date -u +%Y%m%dT%H%M%SZ)"
    mv -- "$target_file" "$backup_file"
    printf '%s\n' "Preserved existing file: $backup_file"
fi

ln -s -- "$source_file" "$target_file"
printf '%s\n' "Linked: $target_file -> $source_file"
