#!/usr/bin/env bash

set -euo pipefail

repo_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source_file="$repo_dir/codex/AGENTS.md"
target_dir="${CODEX_HOME:-$HOME/.codex}"
target_file="$target_dir/AGENTS.md"
private_file="$target_dir/AGENTS.private.md"
generated_marker="<!-- Generated by dotfiles/install.sh from public and private guidance. -->"

mkdir -p "$target_dir"

if [[ -s "$private_file" ]]; then
    temporary_file="$(mktemp "$target_dir/.AGENTS.md.XXXXXX")"
    {
        printf '%s\n\n' "$generated_marker"
        cat -- "$source_file"
        printf '\n\n'
        cat -- "$private_file"
    } > "$temporary_file"

    if [[ -f "$target_file" && ! -L "$target_file" ]] && cmp -s -- "$temporary_file" "$target_file"; then
        rm -- "$temporary_file"
        printf '%s\n' "Already generated: $target_file"
        exit 0
    fi

    if [[ -e "$target_file" || -L "$target_file" ]]; then
        if [[ -L "$target_file" && "$(readlink -f -- "$target_file")" == "$(readlink -f -- "$source_file")" ]]; then
            rm -- "$target_file"
        elif [[ -f "$target_file" && ! -L "$target_file" && "$(head -n 1 -- "$target_file")" == "$generated_marker" ]]; then
            rm -- "$target_file"
        else
            backup_file="$target_file.backup.$(date -u +%Y%m%dT%H%M%SZ)"
            mv -- "$target_file" "$backup_file"
            printf '%s\n' "Preserved existing file: $backup_file"
        fi
    fi

    mv -- "$temporary_file" "$target_file"
    printf '%s\n' "Generated: $target_file from $source_file and $private_file"
    exit 0
fi

if [[ -e "$target_file" || -L "$target_file" ]]; then
    if [[ "$(readlink -f -- "$target_file")" == "$(readlink -f -- "$source_file")" ]]; then
        printf '%s\n' "Already linked: $target_file"
        exit 0
    fi

    backup_file="$target_file.backup.$(date -u +%Y%m%dT%H%M%SZ)"
    mv -- "$target_file" "$backup_file"
    printf '%s\n' "Preserved existing file: $backup_file"
fi

ln -s -- "$source_file" "$target_file"
printf '%s\n' "Linked: $target_file -> $source_file"
