"""Exercise installation in isolated home and configuration directories."""

import os
from pathlib import Path
import shutil
import stat
import subprocess
import tempfile
import unittest


class InstallTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory(prefix='dotfiles-install-')
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name)
        self.repository = self.root / 'repository'
        self.home_directory = self.root / 'home'
        self.configuration = self.root / 'configuration'
        self.home_directory.mkdir()
        self.configuration.mkdir()
        (self.repository / 'codex' / 'agents').mkdir(parents=True)
        shutil.copy2(Path(__file__).resolve().parents[1] / 'install.sh', self.repository / 'install.sh')
        self.guidance = self.repository / 'codex' / 'AGENTS.md'
        self.guidance.write_text('# Public guidance\n')
        self.agent = self.repository / 'codex' / 'agents' / 'luna_lookup.toml'
        self.agent.write_text('name = "luna_lookup"\nmodel_reasoning_effort = "medium"\n')
        self.environment = dict(os.environ)
        self.environment.update(HOME=str(self.home_directory), CODEX_HOME=str(self.configuration))

    def install(self):
        result = subprocess.run(['bash', str(self.repository / 'install.sh')], env=self.environment,
                                text=True, capture_output=True)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        return result

    def add_public_detail(self, name='architecture.md', content='# Public detail\n'):
        detail = self.repository / 'codex' / 'guidance' / name
        detail.parent.mkdir(parents=True, exist_ok=True)
        detail.write_text(content)
        return detail

    def test_installs_regular_agent_files_and_links_public_guidance(self):
        self.install()
        target = self.configuration / 'agents' / self.agent.name
        self.assertTrue(target.is_file(), 'The public agent definition was not installed')
        self.assertFalse(target.is_symlink())
        self.assertEqual(target.read_bytes(), self.agent.read_bytes())
        self.assertEqual(stat.S_IMODE(target.stat().st_mode), 0o600)
        self.assertEqual((self.configuration / 'AGENTS.md').resolve(), self.guidance)

    def test_preserves_a_different_definition_and_unrelated_agent(self):
        agents = self.configuration / 'agents'
        agents.mkdir()
        target = agents / self.agent.name
        target.write_text('original definition\n')
        unrelated = agents / 'personal.toml'
        unrelated.write_text('personal definition\n')
        self.install()
        backups = list(agents.glob(self.agent.name + '.backup.*'))
        self.assertEqual(len(backups), 1)
        self.assertEqual(backups[0].read_text(), 'original definition\n')
        self.assertEqual(target.read_bytes(), self.agent.read_bytes())
        self.assertEqual(unrelated.read_text(), 'personal definition\n')

    def test_preserves_a_legacy_symlink_and_its_source(self):
        agents = self.configuration / 'agents'
        agents.mkdir()
        legacy = self.root / 'legacy.toml'
        legacy.write_text('legacy definition\n')
        target = agents / self.agent.name
        target.symlink_to(legacy)
        self.install()
        self.assertFalse(target.is_symlink())
        self.assertEqual(target.read_bytes(), self.agent.read_bytes())
        self.assertEqual(legacy.read_text(), 'legacy definition\n')
        backups = list(agents.glob(self.agent.name + '.backup.*'))
        self.assertEqual(len(backups), 1)
        self.assertTrue(backups[0].is_symlink())
        self.assertEqual(backups[0].resolve(), legacy)

    def test_repeated_installation_does_not_replace_identical_files(self):
        self.install()
        target = self.configuration / 'agents' / self.agent.name
        self.assertTrue(target.exists(), 'The public agent definition was not installed')
        before = target.stat()
        self.install()
        after = target.stat()
        self.assertEqual((before.st_ino, before.st_mtime_ns), (after.st_ino, after.st_mtime_ns))
        self.assertEqual(list(target.parent.glob('*.backup.*')), [])

    def test_installs_agents_even_when_combined_guidance_is_unchanged(self):
        private = self.configuration / 'AGENTS.private.md'
        private.write_text('# Private guidance\n')
        self.install()
        combined = self.configuration / 'AGENTS.md'
        expected = ('<!-- Generated by dotfiles/install.sh from public and private guidance. -->\n\n'
                    + self.guidance.read_text() + '\n\n' + private.read_text())
        self.assertEqual(combined.read_text(), expected)
        before = combined.stat()
        target = self.configuration / 'agents' / self.agent.name
        if target.exists():
            target.unlink()
        self.install()
        self.assertTrue(target.is_file(), 'The unchanged-guidance path skipped agent installation')
        self.assertEqual(combined.stat().st_mtime_ns, before.st_mtime_ns)
        self.assertEqual(combined.read_text(), expected)

    def test_preserves_existing_guidance_and_installs_skills(self):
        target = self.configuration / 'AGENTS.md'
        target.write_text('# Existing guidance\n')
        skill = self.repository / 'codex' / 'skills' / 'example'
        skill.mkdir(parents=True)
        (skill / 'SKILL.md').write_text('# Example\n')
        self.install()
        backups = list(self.configuration.glob('AGENTS.md.backup.*'))
        self.assertEqual(len(backups), 1)
        self.assertEqual(backups[0].read_text(), '# Existing guidance\n')
        self.assertEqual(target.resolve(), self.guidance)
        self.assertEqual((self.home_directory / '.agents' / 'skills' / 'example').resolve(), skill)

    def test_installs_public_detail_as_a_regular_file(self):
        detail = self.add_public_detail(content='# Public detail only\n')

        self.install()

        target = self.configuration / 'guidance' / 'public' / detail.name
        self.assertTrue(target.is_file(), 'The public detail file was not installed')
        self.assertFalse(target.is_symlink())
        self.assertEqual(target.read_bytes(), detail.read_bytes())
        self.assertEqual(stat.S_IMODE(target.stat().st_mode), 0o600)
        self.assertNotIn('Public detail only', (self.configuration / 'AGENTS.md').read_text())

    def test_preserves_public_detail_replacement_and_other_namespace_files(self):
        detail = self.add_public_detail(content='# Current public detail\n')
        public_guidance = self.configuration / 'guidance' / 'public'
        private_guidance = self.configuration / 'guidance' / 'private'
        public_guidance.mkdir(parents=True)
        old_target = public_guidance / detail.name
        old_target.write_text('# Previous public detail\n')
        unrelated = public_guidance / 'personal.md'
        unrelated.write_text('# Personal detail\n')
        private_detail = private_guidance / 'local.md'
        private_detail.parent.mkdir(parents=True)
        private_detail.write_text('# Private detail\n')

        self.install()

        backups = list(public_guidance.glob(detail.name + '.backup.*'))
        self.assertEqual(len(backups), 1)
        self.assertEqual(backups[0].read_text(), '# Previous public detail\n')
        self.assertEqual(old_target.read_bytes(), detail.read_bytes())
        self.assertFalse(old_target.is_symlink())
        self.assertEqual(stat.S_IMODE(old_target.stat().st_mode), 0o600)
        self.assertEqual(unrelated.read_text(), '# Personal detail\n')
        self.assertEqual(private_detail.read_text(), '# Private detail\n')

    def test_repeated_installation_keeps_identical_public_detail(self):
        detail = self.add_public_detail()
        self.install()
        target = self.configuration / 'guidance' / 'public' / detail.name
        self.assertTrue(target.is_file(), 'The public detail file was not installed')
        before = target.stat()

        self.install()

        after = target.stat()
        self.assertEqual((before.st_ino, before.st_mtime_ns), (after.st_ino, after.st_mtime_ns))
        self.assertEqual(list(target.parent.glob('*.backup.*')), [])

    def test_updates_public_details_when_combined_guidance_is_unchanged(self):
        detail = self.add_public_detail(content='# First detail version\n')
        initial_content = '# First detail version\n'
        (self.configuration / 'AGENTS.private.md').write_text('# Private guidance\n')
        self.install()
        target = self.configuration / 'guidance' / 'public' / detail.name
        combined = self.configuration / 'AGENTS.md'
        combined_before = combined.stat()
        detail.write_text('# Updated detail version\n')

        self.install()

        self.assertTrue(target.is_file(), 'The public detail file was not installed')
        self.assertEqual(target.read_text(), '# Updated detail version\n')
        self.assertEqual(combined.stat().st_mtime_ns, combined_before.st_mtime_ns)
        backups = list(target.parent.glob(detail.name + '.backup.*'))
        self.assertEqual(len(backups), 1)
        self.assertEqual(backups[0].read_text(), initial_content)


if __name__ == '__main__':
    unittest.main()
